config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  scope "us" do
    resources :zip, only: [ :show ], param: :code
  end

  get ":latitude/:longitude/forecast", to: "forecast#show", as: :forecast, constraints: { latitude: /-?\d+(\.\d+)?/, longitude: /-?\d+(\.\d+)?/ }

  resource :geocode, only: [ :new, :create ], controller: "geocode"
  root "geocode#new"
end

app/models/application_model.rb
class ApplicationModel
  include ActiveModel::API
  include ActiveModel::Attributes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/area.rb
class Area < ApplicationModel
  attribute :name, :string
  attribute :latitude, :float
  attribute :longitude, :float
end

app/models/current_condition.rb
class CurrentCondition < ApplicationModel
  attribute :zip_code, :string

  attribute :temperature, :integer
  attribute :feels_like, :integer
  attribute :high, :integer
  attribute :low, :integer
end

app/models/daily_forecast.rb
class  DailyForecast < ApplicationModel
  attribute :date, :date

  # TODO: Extract into a concern
  attribute :temperature, :integer
  attribute :feels_like, :integer
  attribute :high, :integer
  attribute :low, :integer
end

app/models/zip_area.rb
class ZipArea < ApplicationModel
  attribute :code, :string
  attribute :name, :string
  attribute :latitude, :float
  attribute :longitude, :float
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/forecast_controller.rb
class ForecastController < ApplicationController
  def show
    attempt = params.fetch(:attempt, 0).to_i + 1

    @response = OpenWeatherMap::Client.one_call(params[:latitude], params[:longitude])

    if @response.success?
      @daily_forecasts = @response.daily_forecasts

    elsif @response.retryable? && attempt < 3
      redirect_to forecast_path(
        latitude: params[:latitude],
        longitude: params[:longitude],
        attempt:
      )

    else
      render :error, status: :unprocessable_entity
    end
  end
end

app/controllers/geocode_controller.rb
class GeocodeController < ApplicationController
  def new
  end

  def create
    if us_zip_code?
      redirect_to zip_path(geocode_params[:zip_code])
    else
      flash[:error] = "Only US addresses are currently supported."

      render :new, status: :unprocessable_entity
    end
  end

  private

  def geocode_params
    params.permit(:zip_code, :country_code, :authenticity_token)
  end

  def us_zip_code?
    geocode_params[:country_code] == "US" && geocode_params[:zip_code].present?
  end
end

app/controllers/zip_controller.rb
class ZipController < ApplicationController
  def show
    attempt = params.fetch(:attempt, 0).to_i + 1

    @response = OpenWeatherMap::Client.current_weather(params[:code])
    if @response.success?
      @area = @response.area
      @current_condition = @response.current_condition

    elsif @response.retryable? && attempt < 3
      redirect_to zip_path(code: params[:code], attempt:)

    else
      render :error, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def kelvin_to_f(kelvin, precision: 0)
    ((kelvin - 273.15) * 9 / 5 + 32).round(precision)
  end

  def kelvin_to_c(kelvin, precision: 0)
    (kelvin - 273.15).round(precision)
  end
end

app/helpers/forecast_helper.rb
module ForecastHelper
end

app/helpers/geocode_helper.rb
module GeocodeHelper
end

app/helpers/zip_helper.rb
module ZipHelper
end

app/views/forecast/error.html.erb
<%= @response.error_message.presence || "An error occurred" %>
<%= @response.inspect %>

app/views/forecast/show.html.erb
<%= turbo_frame_tag "forecast" do %>
  <div class="bg-neutral-900/20 backdrop-blur-lg border border-neutral-500/10 rounded-lg p-4 text-white mx-auto w-3xs">
    <table class="w-30 table-fixed mx-auto">
      <caption class="caption-top text-sm text-blue-200">
        Daily forecasts
      </caption>

    <% @response.daily_forecasts.each do |forecast| %>
      <% next if forecast.date.today? %>
      <tr>
        <td class="text-right px-2"><%= forecast.date.strftime("%a") %></td>
        <td class="px-2"><%= kelvin_to_f(forecast.temperature) %>°</td>
        <%# <%= forecast.feels_like %>
        <%# <%= forecast.high %>
        <%# <%= forecast.low %>
      </tr>
    <% end %>
    </table>
  </div>
<% end %>

app/views/geocode/new.html.erb
<% content_for :head do %>
  <script id="search-js" defer src="https://api.mapbox.com/search-js/v1.0.0/web.js"></script>
<% end %>

<section class="w-md mx-auto">
  <h1 class="text-2xl mb-2 text-white">Search for a US address</h1>
  <% if @error_message.present? %>
    <%= @error_message %>
  <% end %>

  <%= form_with url: geocode_path, method: :post, data: { controller: "geocode" } do |form| %>
    <mapbox-geocoder
      access-token="pk.eyJ1IjoiZGFpdGVuc2hpbnIiLCJhIjoiY21hZ3d3ZjU4MDVvNjJ3b2s0cTFmYXpheSJ9.eRhMo8YVMC-_ErQg0tvMKw"
      proximity="0,0"
      data-geocode-target="geocoder"
    >
    </mapbox-geocoder>

    <%= form.hidden_field :zip_code, data: { geocode_target: "zipCode" } %>
    <%= form.hidden_field :country_code, data: { geocode_target: "countryCode" } %>

  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Weather Forecast" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-linear-to-t from-cyan-500 to-blue-500 h-screen
">
    <main class="container mx-auto pt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/zip/error.html.erb
<%= @response.error_message.presence || "An error occurred" %>

app/views/zip/show.html.erb
<div class="text-white mx-auto text-center mb-5">
  <h1 class="text-2xl mb-1 ">
    <%= @area.name %>
  </h1>
  <div class="text-white text-6xl">
    <%= kelvin_to_f(@current_condition.temperature) %>°
  </div>
  <div>feels like: <%= kelvin_to_f(@current_condition.feels_like) %>℉</div>

  <div>
    <span><abbr title="high" style="text-decoration: none;">H</abbr>: <%= kelvin_to_f(@current_condition.high) %>°</span>
    <span><abbr title="low" style="text-decoration: none;">L</abbr>: <%= kelvin_to_f(@current_condition.low) %>°</span>
  </div>

  <% unless @response.recent? %>
    <div class="text-sm italic text-blue-200">
    as of <%= time_tag @response.cached_on, time_ago_in_words(@response.cached_on) %> ago
    </div>
  <% end %>
</div>

<%= turbo_frame_tag "forecast", src: forecast_path(@area.latitude, @area.longitude) do %>

<% end %>